### ISSUE TITLE
BUG: Log messages not thread-safe?

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-cpp#282]
While trying to debug some of the recent issues with IO, I set the log mode to "debug" level and this led to segfaults in `InformationWindow::writeToLog` in various places, such as:
```
        ui->m_pTextBrowser_Log->insertPlainText("\n"); // new line
```
I think this is because I put some `qDebug` calls in the writing code, and the current logging system is not thread safe, as pointed out by [this StackOverflow post](http://stackoverflow.com/a/22486961/2175965):

> inside main() in main.cpp, before initializing QApplication instance.
>
>     qInstallMessageHandler(myMessageOutput);
>
> Note: This works wonderfully for any single threaded application. Once you start using qDebug() outside your GUI thread, you will crash.

Fortunately they also provide a simple-looking solution using `Qt::QueuedConnection`. My Qt signal/slot skills are a bit rusty, though, so it might take me a while to try to figure out the solution if I tackle it. If someone can comment on if this is the right direction, I can at least give it a try unless someone else is keen to fix it.

**Comment by Eric89GXL** [comment]
I finally figured this out while debugging a problem with MaxShield and TRIUX data visualization. Should I push fixes for this + MaxShield + TRIUX channel types?
