### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by sarthakcbica** [mne-tools/mne-cpp#288]
Awesome work with this! Do you have plans to do this with CMake support?

**Comment by LorenzE** [comment]
Thx for the feedback! Support for CMake is not planned as of right now. QMake (for now) is providing all we need and is especially conveneient to use when coding with QtCreator. However, I looked into QMake - CMake transforming and found the following website: http://www.executionunit.com/blog/2014/01/22/moving-from-qmake-to-cmake/ I am not sure what exactly you are planning to do but if you, i.e, want to use a different IDE you can try using the qt plugin for visual studio or use qmake flags to create a visual studio project (http://doc.qt.io/qt-5/qmake-platform-notes.html#creating-visual-studio-project-files). I hope this helps. If you have more questions please feel free to ask :)
