### ISSUE TITLE
FIX/BUG builds for mac leave GUI unresponsive 

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-cpp#290]

**Comment by dengemann** [comment]
Checking out fresh builds and the ones you have on the website on my mac os sierra browse raw is extremely unresponsive. I suspect the builds are somehow not optimized, maybe not using hardware acceleration, etc.

**Comment by LorenzE** [comment]
This should have been fixed by PR #361, which introduced (GPU) hardware acceleration.
