### ISSUE TITLE
Neuromag Connector: Listener/Passive Mode

### ISSUE THREAD

**Issue by cpieloth** [mne-tools/mne-cpp#33]
This is a feature request to extend the Neuromag Connector by a passive or listener-only mode.

Starting point:
We implement a rt_client for our OpenWalnut-based software to link it to a mne_rt_server (using the mne lib). The connection is working well. Our user is using the Neuromag Acquisition Software for a measurement and wants to test our software without any impact on the current workflow.

Problem:
The record raw function of Neuromag Acquisition Software is disabled when mne_rt_server is starting a measurement. We need the possibility to control the MEG system by the Neuromag Acquisition Software (start, stop, and specifically record) and simultaneously streaming a running measurement.
This has two reasons:
1) The user wants to control the system by the well known Neuromag Acquisition Software. Our software is used as an optional extension and should not change or interrupt a running measurement/experiment. 
2) Our client software has a very high computational load in CPU and I/O. This could result in a data loss, if our client is recording a measurement at the same time.

Idea:
1) A dedicated and light client for controlling and recording:
A separated client could replace the Neuromag Acquisition Software (for controlling and recording). This client runs locally on the MEG workstation and connects as a data and control client to the mne_rt_server. The client can record the measurement locally. Our software connects to the mne_rt_server as a second data client and is just receiving and computing the data.
CONS: We introduce a third tool for the user.

2) Extend the NeuromagConnector by a Listener/Passive Mode:
The NeuromagConnector has the ability to read the data of a running measurement, which was started by the Neuromag Acquisition Software. A setting like ACTIVE/PASSIVE mode could be used to switch between the listener-only ability.
PROS: The user can use the Neuromag Acquisition Software to control and record the measurement and the mne_rt_server is running as an "invisible" daemon.
CONS: Modification of NeuromagConnector is needed.

3) Extend the mne_rt_server by a record feature:
The mne_rt_server is extended by a feature to record a measurement locally to a file. 
PROS: This feature can be used by other connectors, too. No extra tool is introduced. Data acquisition/storage and processing/analysing is separated.

4) Any other idea?

With the current knowledge I would prefer 2 or 3.

**Comment by LorenzE** [comment]
@chdinh was the passive mode ever merged to our repository? @puolival would like to use mne_rt_server in safety critical (clinical) environment.

**Comment by LorenzE** [comment]
Closing this issue. The Neuromag plugin in mne_rt_Server has been replaced by the fieldtrip buffer plugin in MNE Scan.
