### ISSUE TITLE
Return Code for a Command response

### ISSUE THREAD

**Issue by cpieloth** [mne-tools/mne-cpp#34]
This is a feature request for a Return Code for a Command response.

Problem:
After sending a Command from a rt client to a mne_rt_server, there is no possibility to check whether it was successful or not.

Idea:
Extend the JSON response by a return code e.g. status with values 0 for success, 1 for a general error, >1 for command specific errors. Additionally something like a optional status text/description could be very helpful for debugging and user output. A third argument contains the actual response.

Example:
Request -> conlist
JSON Response - >success

``` json
{
   status: 0,
   response: 
   {
      // JSON object for the connector list
   }
}
```

JSON Response -> error

``` json
{
   status: 1,
   status_message: "Unknown error while loading server plugins!"
}
```

A command client can check/return the success of a command and an application can handle errors.

**Comment by LorenzE** [comment]
Closing this issue. The Neuromag plugin in mne_rt_Server has been replaced by the fieldtrip buffer plugin in MNE Scan.
