### ISSUE TITLE
Rename MNEEstimateTreeItem in Disp3D

### ISSUE THREAD

**Issue by LorenzE** [mne-tools/mne-cpp#370]
Rename MNEEstimateTreeItem to MNEDataTreeItem. This includes renaming the header and cpp files as well. https://github.com/mne-tools/mne-cpp/blob/f7a125f467fe745baa54615b9044bc35d06b3bbf/libraries/disp3D/engine/model/items/sourcedata/mneestimatetreeitem.h#L109

**Comment by juangpc** [comment]
🙌
