### ISSUE TITLE
Organization wide Code of Conduct

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-cpp#418]
Hi MNE-CPP folks!

We wanted to add a Code of Conduct at the mne-bids repo https://github.com/mne-tools/mne-bids/issues/315 and the discussion emerged whether we could have an organization wide code of conduct.

This is supported by GitHub, see here: https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file-for-your-organization

@larsoner and @agramfort are on board. What are your opinions @LorenzE et al.?

> You can add default community health files for your organization to the root of a public repository called .github that is owned by the organization. GitHub will use and display default files for any public repository in the organization that does not have its own file of that type in any of the following places ...

**Comment by LorenzE** [comment]
Sounds good to me!

**Comment by sappelhoff** [comment]
Cool, thanks for the swift reply. :-)
