### ISSUE TITLE
:-1: error: LNK1104: Datei "MNE1Connectivity.lib" kann nicht geöffnet werden.

### ISSUE THREAD

**Issue by evko6688** [mne-tools/mne-cpp#458]
Since today, compiling stops with the error

:-1: error: LNK1104: Datei "MNE1Connectivity.lib" kann nicht geöffnet werden.

**Comment by RDoerfel** [comment]
Hi @evko6688,
this error occurs when you still have an application running, that uses this library. Did you try to close everything and build or rebuild again?

**Comment by evko6688** [comment]
Hi @RDoerfel,

yes this and I also deleted all files and pulled the whole mne-cpp again, twice, same error.

**Comment by LorenzE** [comment]
@evko6688 Did you remove the shadow build as well? Should be in the same folder as your repository and named something like `build-mne-cpp-Desktop_Qt_5_14_0_MSVC2017_64bit-Release`

**Comment by evko6688** [comment]
Yes. I removed it aswell.

**Comment by LorenzE** [comment]
can you find out from the compiler log where it stopped and the error occurred?

**Comment by LorenzE** [comment]
@evko6688 Were you able to get rid of the linking error?

**Comment by evko6688** [comment]
Have another problem, cannot download/re-pull the mne-cpp, would need some TeamViewer help

**Comment by LorenzE** [comment]
what have you tried so far? is it a git specific problem?

**Comment by evko6688** [comment]
Sync, copy the link of my "fork", Tortoise pull, Tortoise rebase, ..., reinstall Git and Tortoise, ... seems to be a general error from my side

Access denied was a often failure during the download.

**Comment by LorenzE** [comment]
I sounds you are trying to setup a completely new local copy of your remote/forked repository? I would use `clone` instead of `sync`. Also, can you try to use the cmd line (Eingabeaufforderung) instead of TortoiseGit? 

With the cmd tool navigate to your local repository and follow the instructions from section `Get the Source Code` described [here](https://mne-cpp.github.io/pages/install/buildguide.html#get-the-source-code).

**Comment by evko6688** [comment]
Problem solved.
Yes, I tried to setup a new local copy of forked repository. With cmd it worked properly. Also the error: LNK1104: Datei "MNE1Connectivity.lib" kann nicht geöffnet werde does not appear any more.

So problem solved.
