### ISSUE TITLE
mne scan plugins

### ISSUE THREAD

**Issue by juangpc** [mne-tools/mne-cpp#530]
Hi, 
I’m trying to understand the whole plugin tools mne-scan. When I go and see plugin loading method https://github.com/mne-tools/mne-cpp/blob/e8b475537310638d64ed790f3a23f1d7b03ac545/applications/mne_scan/libs/scShared/Management/pluginmanager.cpp#L97
  I don’t know but to mee that seems just weird. Why the object casting? Why not use dynamic binding?

**Comment by LorenzE** [comment]
We do object casting when we build a static version of MNE Scan. This way the plugins are included in the binary directly. This is needed, e.g., when building against wasm. If the static flag is not set, which is mainly the case, we load the plugins dynamically.
