### ISSUE TITLE
Avoid building Qt statically in CI

### ISSUE THREAD

**Issue by LorenzE** [mne-tools/mne-cpp#575]
Avoid building Qt statically in CI by hosting pre-built static Qt versions ourselves. This way we should be able to include static mne-cpp builds to our PR checks as well.

One idea is to create a new workflow script which would build the static versions and upload them via the [upload artifact action](https://github.com/actions/upload-artifact). We could then download the artifacts, host them on our servers and make use of the in the devbuilds.yml workflow file.

**Comment by juangpc** [comment]
Would you want to generate some kind of

**Comment by LorenzE** [comment]
I was more thinking of building Qt statically (and for wasm) via a Github actions workflow for different platforms, upload the zip file as artifact and host them somehwere on a server. This way we could skip the Qt compilation from source in the devbuilds.yml workflow. This would make make budiling a static version of mne-cpp much faster and we could also include static build checks into the PR checks.
