### ISSUE TITLE
MNE Analyze: Annotation markers are moving after scrolling through the file

### ISSUE THREAD

**Issue by RDoerfel** [mne-tools/mne-cpp#659]
![image](https://user-images.githubusercontent.com/40984141/86491897-76794c80-bd6c-11ea-8928-95e615764b94.png)
As presented in the screeenshot, the annotation markers moved after scrolling them out of the view and back. They were originally placed exactly at the events in the Stim Channel. The values in the Annotation settings manager stay the same.

**Comment by LorenzE** [comment]
does this happen when filters deactivated?

**Comment by RDoerfel** [comment]
I'm likely to say yes, but I will double check and let you know.

**Comment by RDoerfel** [comment]
I tried again and it also happens with filter disabled. But I think that is more an issue of the scrolling then the annotations. When scrolling right and back to the left end of the file, I could observe that it starts at a different point.
