### ISSUE TITLE
Neuromag Connector: SegFault when setting Buffer Size after a MeasInfo request

### ISSUE THREAD

**Issue by cpieloth** [mne-tools/mne-cpp#72]
The Neuromag Connector is running into a segmentation fault, if you set the buffer size after a measurement info request.

```
// Pseudo code
// BEGIN: OK
bufsize.send()
...
measinfo.send()
...
start.send()
...
// END: OK

// BEGIN: SegFault
measinfo.send()
...
bufsize.send()
...
start.send()
// crash: segmentation fault
// END: SegFault
```

**Comment by LorenzE** [comment]
Closing this issue. The Neuromag plugin in mne_rt_Server has been replaced by the fieldtrip buffer plugin in MNE Scan.

**Comment by LorenzE** [comment]
Closing this issue. The Neuromag plugin in mne_rt_Server has been replaced by the fieldtrip buffer plugin in MNE Scan.
